{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.shadow",
    "module": "aar-to-jar-plugin",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aar-to-jar-plugin-1.0.jar",
          "url": "aar-to-jar-plugin-1.0.jar",
          "size": 5222,
          "sha512": "560e287109d5c7662734da8a755a27c17f00ce36fa9601a19a435613cca1c55b69d8a1629ad5b0bd194d90d8ce68a87dfac183c5ff28e939c6cd59506919fcb9",
          "sha256": "ed254f6f07aa1152251c5187f7d9a32a83b1bcabb742cc568d9b56b1b2335d93",
          "sha1": "20b36777c1e93e1cad31481cb00c2ab71d1e8d0f",
          "md5": "fe259be7397996d22fcfd12881e61a55"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "aar-to-jar-plugin-1.0.jar",
          "url": "aar-to-jar-plugin-1.0.jar",
          "size": 5222,
          "sha512": "560e287109d5c7662734da8a755a27c17f00ce36fa9601a19a435613cca1c55b69d8a1629ad5b0bd194d90d8ce68a87dfac183c5ff28e939c6cd59506919fcb9",
          "sha256": "ed254f6f07aa1152251c5187f7d9a32a83b1bcabb742cc568d9b56b1b2335d93",
          "sha1": "20b36777c1e93e1cad31481cb00c2ab71d1e8d0f",
          "md5": "fe259be7397996d22fcfd12881e61a55"
        }
      ]
    }
  ]
}
