{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.shadow",
    "module": "aar-to-jar-plugin",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aar-to-jar-plugin-1.0.jar",
          "url": "aar-to-jar-plugin-1.0.jar",
          "size": 5222,
          "sha512": "3aeb991c5849bdf9bb9a3360aa7b30f58ce27f1591858baf8e733772c15390a2933a4be8539edb72e4eff91887c1d90d60d0a159f7e46a055d5974e9c9dd1078",
          "sha256": "57cc5cc88dbeb9d79e0cec70c84ce23b57a0d800c197459378c249831e184b4c",
          "sha1": "4f19b65bcd624646e97d9b3b12942373c50f0401",
          "md5": "8aa72dedeb8770a4ee91e47a3a929856"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "aar-to-jar-plugin-1.0.jar",
          "url": "aar-to-jar-plugin-1.0.jar",
          "size": 5222,
          "sha512": "3aeb991c5849bdf9bb9a3360aa7b30f58ce27f1591858baf8e733772c15390a2933a4be8539edb72e4eff91887c1d90d60d0a159f7e46a055d5974e9c9dd1078",
          "sha256": "57cc5cc88dbeb9d79e0cec70c84ce23b57a0d800c197459378c249831e184b4c",
          "sha1": "4f19b65bcd624646e97d9b3b12942373c50f0401",
          "md5": "8aa72dedeb8770a4ee91e47a3a929856"
        }
      ]
    }
  ]
}
