{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.shadow",
    "module": "aar-to-jar-plugin",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aar-to-jar-plugin-1.0.jar",
          "url": "aar-to-jar-plugin-1.0.jar",
          "size": 5222,
          "sha512": "69e30d214339a5a68c706bc527c39fc4b5b9405976d2ca34d662d6f34ae1ada0548b5aeaeec50d87921e463047e33f08a080bb84e12b820588f5b487d39fa25b",
          "sha256": "4b614d60df22935cfcdd8e99a3511d40bcf49848f0eb075f7a0fda223054b617",
          "sha1": "833916f34eb4bbfed34b8b132b4e91b5ad9b5a3f",
          "md5": "8514f691eaa0f6a319ce85a3af3afab4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "aar-to-jar-plugin-1.0.jar",
          "url": "aar-to-jar-plugin-1.0.jar",
          "size": 5222,
          "sha512": "69e30d214339a5a68c706bc527c39fc4b5b9405976d2ca34d662d6f34ae1ada0548b5aeaeec50d87921e463047e33f08a080bb84e12b820588f5b487d39fa25b",
          "sha256": "4b614d60df22935cfcdd8e99a3511d40bcf49848f0eb075f7a0fda223054b617",
          "sha1": "833916f34eb4bbfed34b8b132b4e91b5ad9b5a3f",
          "md5": "8514f691eaa0f6a319ce85a3af3afab4"
        }
      ]
    }
  ]
}
