{
  "formatVersion": "1.1",
  "component": {
    "group": "com.qihoo360.replugin",
    "module": "replugin-host-gradle",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "replugin-host-gradle-3.1.0.jar",
          "url": "replugin-host-gradle-3.1.0.jar",
          "size": 187556,
          "sha512": "cb208930a9bb78dde6b52514aa10883195d08699f5ecb90aaa405881236f71d99bcd5203a90f1192eef6cbc8b6ba3f1679e3816dc7cee6f2618901dc3d929e6b",
          "sha256": "7c1214c5f980a15617807e3f56bfb81075a77184a1a8d82347dac85a01ed5a29",
          "sha1": "91ff557f05589fe1d5e11cae67c98e9bf7061278",
          "md5": "6b07816e724160c294d805181951d6e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20160212"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "2.4.7"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.gradle",
          "module": "osdetector-gradle-plugin",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "net.dongliu",
          "module": "apk-parser",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "replugin-host-gradle-3.1.0.jar",
          "url": "replugin-host-gradle-3.1.0.jar",
          "size": 187556,
          "sha512": "cb208930a9bb78dde6b52514aa10883195d08699f5ecb90aaa405881236f71d99bcd5203a90f1192eef6cbc8b6ba3f1679e3816dc7cee6f2618901dc3d929e6b",
          "sha256": "7c1214c5f980a15617807e3f56bfb81075a77184a1a8d82347dac85a01ed5a29",
          "sha1": "91ff557f05589fe1d5e11cae67c98e9bf7061278",
          "md5": "6b07816e724160c294d805181951d6e5"
        }
      ]
    }
  ]
}
