apply plugin: 'com.android.library'
apply plugin: 'com.tencent.shadow.internal.aar-to-jar'
apply plugin: 'org.jetbrains.kotlin.android'


android {
    compileSdkVersion project.COMPILE_SDK_VERSION
    namespace 'com.plugins.host.lib'


    defaultConfig {
        minSdkVersion project.MIN_SDK_VERSION
        targetSdkVersion project.TARGET_SDK_VERSION
        versionCode project.VERSION_CODE
        versionName project.VERSION_NAME

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            consumerProguardFiles 'sample-host-lib.pro'
        }
    }

}
dependencies {

    constraints {
        implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android") {
            version { strictly("1.7.3") } // Kotlin 1.9.x官方推荐协程版本
        }
        implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core") {
            version { strictly("1.7.3") }
        }
    }

//    implementation("androidx.lifecycle:lifecycle-common:2.6.1") // 保持原版本
//    implementation 'androidx.activity:activity:1.7.1'
//
//    implementation 'androidx.appcompat:appcompat:1.4.1'


    implementation 'androidx.lifecycle:lifecycle-viewmodel:2.6.1'
    implementation 'androidx.lifecycle:lifecycle-livedata-core:2.6.1'
}
