plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.launcher.ui3'
    compileSdk 34

    defaultConfig {
        applicationId "com.launcher.ui3"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    // 修改 APK 名称
    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            output.outputFileName = "LauncherUI3.apk"
        }
    }
    buildFeatures {
        viewBinding true
    }
    signingConfigs {
        debug {
            storeFile file('../../../keystore/platform.jks')
            keyAlias 'platform'
            keyPassword 'android'
            storePassword 'android'
        }
        release {
            storeFile file('../../../keystore/platform.jks')
            keyAlias 'platform'
            keyPassword 'android'
            storePassword 'android'
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    aaptOptions {
        additionalParameters '--allow-reserved-package-id', '--package-id', '0x7e'
    }
}


def isPlugin = false


if (isPlugin) {
    apply plugin: 'replugin-plugin-gradle'
} else {
    apply plugin: 'replugin-host-gradle'
}

dependencies {

    /** compileOnly or implementation */
    //if (rootProject.ext.isPlugin) {
    if (isPlugin) {

        implementation(libs.replugin.plugin.lib)

        // 作为插件，compileOnly 方式引入
        compileOnly libs.appcompat

        compileOnly project(path: ':app')
        compileOnly project(path: ':AwellLibrary')

        //编译期 不会打包
        annotationProcessor 'com.github.bumptech.glide:compiler:4.16.0'

        compileOnly(libs.okhttp3.integration) {
            exclude group: 'androidx.core', module: 'core'
            exclude group: 'androidx.interpolator', module: 'interpolator'
            exclude group: 'org.jetbrains.kotlin'
            exclude group: 'org.jetbrains.kotlinx'
        }

        implementation(libs.constraintlayout) {
            exclude group: 'androidx.appcompat'
            exclude group: 'androidx.core'
            exclude group: 'androidx.fragment'
        }

    } else {


        implementation(project(':app')) {
        }

        implementation(libs.appcompat)

        //app module has
        compileOnly libs.constraintlayout

        //system has
        compileOnly project(path: ':AwellLibrary')

        annotationProcessor 'com.github.bumptech.glide:compiler:4.16.0'

        //app module has
        compileOnly(libs.okhttp3.integration) {
            exclude group: 'androidx.core', module: 'core'
            exclude group: 'androidx.interpolator', module: 'interpolator'
            exclude group: 'org.jetbrains.kotlin'
            exclude group: 'org.jetbrains.kotlinx'
        }
    }
}


if (isPlugin) {
    repluginPluginConfig {
        //插件名
        pluginName = "plugin3"
        //宿主app的包名
        hostApplicationId = "com.awell.launcher"
        //宿主app的启动activity
        hostAppLauncherActivity = "com.awell.launcher.MainActivity"
//    ignoredInjectors = ['LoaderActivityInjector', 'ProviderInjector']
    }
}