// Top-level build file where you can add configuration options common to all sub-projects/modules.


buildscript {
    loadVersions:
    {// 读取versions.properties到ext中，供项目中直接用变量引用版本号
        def versions_properties_path = 'buildScripts/gradle/versions.properties'
        def versions = new Properties()
        versions.load(file(versions_properties_path).newReader())
        versions.forEach { key, stringValue ->
            def value = stringValue?.isInteger() ? stringValue as Integer : stringValue
            ext.set(key, value)
        }
    }
    ext.SAMPLE_HOST_APP_APPLICATION_ID = 'com.awell.launcher'

    repositories {
        maven {
            url = './libs/maven'   // 或者使用绝对路径，但相对路径更易于移植
        }
        mavenLocal()
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }

    ext.kotlin_version = '1.9.24' // 统一使用这个版本
    ext.coroutines_version = "1.7.3"

    ext{
        // 定义共享的宿主app包名和启动activity
        hostApplicationId = "com.awell.launcher.host"
        hostAppLauncherActivity = "com.awell.launcher.host.MainActivity"
    }

    dependencies {
        classpath "com.android.tools.build:gradle:7.4.2"

        // 其他依赖...
//        classpath "com.tencent.shadow:aar-to-jar-plugin:1.0" // 替换成你发布的版本
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
//        classpath 'com.tencent.shadow.core:gradle-plugin:1.0'

        classpath libs.replugin.host.gradle
        classpath libs.replugin.plugin.gradle

    }
}


static def log(message) {
    System.err.println ">>> [DEBUG] [huang] ${new Date().format('HH:mm:ss.SSS')} ${message}"
}

plugins {
    id 'com.android.application' version '7.4.0' apply false
    id 'com.android.library' version '7.4.0' apply false
    id 'org.jetbrains.kotlin.android' version '1.9.24' apply false
}