pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

def mavenRepoUrl = providers.gradleProperty('MAVEN_REPO_URL').orElse('./libs/maven').get()

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven {
            url = uri(mavenRepoUrl)
        }
        mavenLocal()
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
rootProject.name = "Launcher2_awell"
include ':app', ':AwellLibrary'
include ':plugin:plugins:ui1'
include ':launcher'
include ':plugin:plugins:ui2'
include ':plugin:plugins:ui3'
include ':plugin:plugins:ui4'
include ':plugin:plugins:ui5'
include ':plugin:plugins:ui6'
include ':plugin:plugins:ui7'
include ':plugin:plugins:yfd_ui01'
include ':plugin:plugins:ui8'
include ':plugin:plugins:ui9'
include ':plugin:plugins:ui10'
include ':plugin:plugins:ui11'
include ':plugin:plugins:yfd_ui2'
include ':plugin:plugins:ui12'
include ':plugin:plugins:ui13'
include ':plugin:plugins:ui14'
include ':plugin:plugins:ui16'
include ':plugin:plugins:ui19'
include ':plugin:plugins:ui20'
include ':plugin:plugins:yfd_ui03'
include ':plugin:plugins:zy_ui01'
include ':plugin:plugins:zy_ui02'
include ':plugin:plugins:zy_ui03'

