{
  "formatVersion": "1.1",
  "component": {
    "group": "com.qihoo360.replugin",
    "module": "replugin-plugin-gradle",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "replugin-plugin-gradle-3.1.0.jar",
          "url": "replugin-plugin-gradle-3.1.0.jar",
          "size": 169967,
          "sha512": "fb6c28ac056b2791b9fe570db93b87b25cce202230a8b03bf7759eb711aa70f2ed169fa891f8a5d50da6b5eecfc140a5b6513a08724dfb6bc121003f094efb7c",
          "sha256": "5aae39bbf3d0f10ae93c085a1c85e62be49be41365ab1192299597ff8545e39f",
          "sha1": "c0033371acdf5f30dc651990feea1467abd1580a",
          "md5": "e9d80da806866a251c6209c1a447e296"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20160212"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "2.4.7"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "transform-api",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.18.2-GA"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.11"
          }
        }
      ],
      "files": [
        {
          "name": "replugin-plugin-gradle-3.1.0.jar",
          "url": "replugin-plugin-gradle-3.1.0.jar",
          "size": 169967,
          "sha512": "fb6c28ac056b2791b9fe570db93b87b25cce202230a8b03bf7759eb711aa70f2ed169fa891f8a5d50da6b5eecfc140a5b6513a08724dfb6bc121003f094efb7c",
          "sha256": "5aae39bbf3d0f10ae93c085a1c85e62be49be41365ab1192299597ff8545e39f",
          "sha1": "c0033371acdf5f30dc651990feea1467abd1580a",
          "md5": "e9d80da806866a251c6209c1a447e296"
        }
      ]
    }
  ]
}
