//plugins {
//    id 'com.android.application'
//}

apply plugin: 'com.android.application'
apply plugin: 'org.jetbrains.kotlin.android'

apply plugin: 'replugin-host-gradle'

android {
    namespace 'com.awell.launcher.host'
    compileSdk 34

    defaultConfig {
        applicationId "com.awell.launcher.host"
        minSdk 26
        targetSdk 34
        versionCode 10
        versionName "1.10"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    // 修改 APK 名称
    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            output.outputFileName = "LauncherHost.apk"
        }
    }
    buildFeatures {
        viewBinding true
    }
    signingConfigs {
        debug {
            storeFile file('../keystore/platform.jks')
            keyAlias 'platform'
            keyPassword 'android'
            storePassword 'android'
        }
        release {
            storeFile file('../keystore/platform.jks')
            keyAlias 'platform'
            keyPassword 'android'
            storePassword 'android'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
    }

    sourceSets {
        debug {
            assets.srcDir('build/generated/assets/manager/debug/')
            assets.srcDir('build/generated/assets/plugin-zip/debug/')
        }
        release {
            assets.srcDir('build/generated/assets/manager/release/')
            assets.srcDir('build/generated/assets/plugin-zip/release/')
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

repluginHostConfig {
    useAppCompat = true
    useAndroidX = true
    // 可以在这里自定义常驻进程的名字
    // persistentName = ":XXXXService"
}

dependencies {

    implementation libs.replugin.host.lib

    //app module has
    compileOnly libs.constraintlayout

    implementation 'androidx.lifecycle:lifecycle-viewmodel:2.6.1'
    implementation 'androidx.lifecycle:lifecycle-livedata-core:2.6.1'

    implementation project(path: ':app')

    compileOnly project(path: ':AwellLibrary')

}
