//plugins {
//    id 'com.android.application'
//}

apply plugin: 'com.android.application'
apply plugin: 'com.tencent.shadow.plugin'
apply plugin: 'org.jetbrains.kotlin.android'

android {
    namespace 'com.awell.launcher'
    compileSdk 34

    defaultConfig {
        applicationId "com.awell.launcher"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildFeatures {
        viewBinding true
    }
    signingConfigs {
        debug {
            storeFile file('../keystore/platform.jks')
            keyAlias 'platform'
            keyPassword 'android'
            storePassword 'android'
        }
        release {
            storeFile file('../keystore/platform.jks')
            keyAlias 'platform'
            keyPassword 'android'
            storePassword 'android'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    sourceSets {
        debug {
            assets.srcDir('build/generated/assets/manager/debug/')
            assets.srcDir('build/generated/assets/plugin-zip/debug/')
        }
        release {
            assets.srcDir('build/generated/assets/manager/release/')
            assets.srcDir('build/generated/assets/plugin-zip/release/')
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {

    constraints {
        implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android") {
            version { strictly("1.7.3") } // Kotlin 1.9.x官方推荐协程版本
        }
        implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core") {
            version { strictly("1.7.3") }
        }
    }
    implementation("androidx.lifecycle:lifecycle-common:2.6.1") // 保持原版本
    implementation 'androidx.activity:activity:1.7.1'

    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'com.tencent.shadow.dynamic:host:1.0'

    implementation 'androidx.constraintlayout:constraintlayout:2.0.1'

    implementation 'androidx.lifecycle:lifecycle-viewmodel:2.6.1'
    implementation 'androidx.lifecycle:lifecycle-livedata-core:2.6.1'

    implementation project(path: ':app')
    implementation project(path: ':AwellLibrary')
    implementation project(':plugin:plugins:constant')
    implementation project(':plugin:plugins:host-lib')


}


def createCopyTask(projectName, buildType, name, apkName, inputFile, taskName) {
    def outputFile = file("${getBuildDir()}/generated/assets/${name}/${buildType}/${apkName}")
    outputFile.getParentFile().mkdirs()
    log(" createCopyTask ")
    return tasks.create("copyAssets${buildType.capitalize()}${name.capitalize()}Task", Copy) {
        group = 'build'
        description = "复制${name}到assets中."

        log(" Copy copy${buildType.capitalize()}${name.capitalize()}Task file =>${inputFile.name} file exits=${inputFile.exists()}")

        from(inputFile.getParent()) {
            include(inputFile.name)
            rename { outputFile.name }
        }
        into(outputFile.getParent())

    }.dependsOn("${projectName}:${taskName}")
}

def generateAssets(generateAssetsTask, buildType) {

    def moduleName = 'manager'
    def pluginManagerApkFile = file(
            "${project(":plugin:plugins:manager").getBuildDir()}" +
                    "/outputs/apk/${buildType}/" +
                    "${moduleName}-${buildType}.apk"
    )

    def sourceApkFile = file(
            "${project(":plugin:plugins:manager").getBuildDir()}" +
                    "/intermediates/apk/${buildType}/" +
                    "${moduleName}-${buildType}.apk"
    )

    def validApkFile = file(
            "${project(":plugin:plugins:manager").getBuildDir()}" +
                    "/intermediates/apk/${buildType}/" +
                    "${moduleName}-${buildType}.apk")

    if (pluginManagerApkFile.exists()) {
        validApkFile = pluginManagerApkFile
    } else if (sourceApkFile.exists()) {
        validApkFile = sourceApkFile
    }
    log("manager apk file exist?=${validApkFile.exists()} path=${validApkFile.path}")
    generateAssetsTask.dependsOn createCopyTask(
            ':plugin:plugins:manager',
            buildType,
            moduleName,
            'pluginmanager.apk',
            validApkFile,
            "assemble${buildType.capitalize()}"
    )

    def pluginZip = file("${getRootProject().getBuildDir()}/plugin-${buildType}.zip")
    log("plugin zip file exist?=${pluginZip.exists()} path=${pluginZip.path}")
    generateAssetsTask.dependsOn createCopyTask(
            ':launcher',
            buildType,
            'plugin-zip',
            "plugin-${buildType}.zip",
            pluginZip,
            "package${buildType.capitalize()}Plugin"
    )
}


tasks.whenTaskAdded { task ->
    if (task.name == "generateDebugAssets") {
        generateAssets(task, 'debug')
    }
    if (task.name == "generateReleaseAssets") {
        generateAssets(task, 'release')
    }
    if (task.name == "generateNormalDebugAssets") {
        generateAssets(task, 'debug')
    }
    if (task.name == "generateNormalReleaseAssets") {
        generateAssets(task, 'release')
    }
}


shadow {
    transform {
//        useHostContext = ['abc']
    }

    packagePlugin {
        pluginTypes {
            debug {
                loaderApkConfig = new Tuple2('loader-debug.apk', ':plugin:plugins:loader:assembleDebug')
                runtimeApkConfig = new Tuple2('runtime-debug.apk', ':plugin:plugins:runtime:assembleDebug')
                pluginApks {
                    pluginApk1 {
                        businessName = 'plugin-app'
                        partKey = 'plugin-app'
                        buildTask = ':plugin:plugins:plugin_1:assemblePluginDebug'
                        apkPath = 'plugin/plugins/plugin_1/build/intermediates/apk/plugin/debug/plugin_1-plugin-debug.apk'
                        hostWhiteList = ["com.tencent.shadow.sample.host.lib", "com.awell.launcher.databinding",
                                         "com.awell.control", "com.awell.model", "com.awell.utils",
                                         "com.awell.launcher2", "com.awell.ctrlview", "androidx.recyclerview.widget"]
                    }
//                    pluginApk2 {
//                        businessName = 'plugin2-app'
//                        partKey = 'plugin2-app'
//                        buildTask = ':plugin:plugins:plugin_2:assemblePluginDebug'
//                        apkPath = 'plugin/plugins/plugin_2/build/intermediates/apk/plugin/debug/plugin_2-plugin-debug.apk'
//                        hostWhiteList = ["com.tencent.shadow.sample.host.lib", "com.awell.launcher.databinding",
//                                         "com.awell.control", "com.awell.model", "com.awell.utils",
//                                         "com.awell.launcher2", "com.awell.ctrlview", "androidx.recyclerview.widget"]
//                    }
                }
            }

            release {
                loaderApkConfig = new Tuple2('loader-release.apk', ':plugin:plugins:loader:assembleRelease')
                runtimeApkConfig = new Tuple2('runtime-release.apk', ':plugin:plugins:runtime:assembleRelease')
                pluginApks {
                    pluginApk1 {
                        businessName = 'plugin-app'
                        partKey = 'plugin-app'
                        buildTask = ':plugin:plugins:plugin_1:assemblePluginRelease'
                        apkPath = 'plugin/plugins/plugin_1/build/intermediates/apk/plugin/release/plugin_1-plugin-release.apk'
                        hostWhiteList = ["com.tencent.shadow.sample.host.lib", "com.awell.launcher.databinding",
                                         "com.awell.control", "com.awell.model", "com.awell.utils",
                                         "com.awell.launcher2", "com.awell.ctrlview", "androidx.recyclerview.widget"]
                    }
//                    pluginApk2 {
//                        businessName = 'plugin2-app'
//                        partKey = 'plugin2-app'
//                        buildTask = ':plugin:plugins:plugin_2:assemblePluginDebug'
//                        apkPath = 'plugin/plugins/plugin_2/build/intermediates/apk/plugin/debug/plugin_2-plugin-debug.apk'
//                        hostWhiteList = ["com.tencent.shadow.sample.host.lib", "com.awell.launcher.databinding",
//                                         "com.awell.control", "com.awell.model", "com.awell.utils",
//                                         "com.awell.launcher2", "com.awell.ctrlview", "androidx.recyclerview.widget"]
//                    }
                }
            }
        }

        loaderApkProjectPath = 'plugin/plugins/loader'
        runtimeApkProjectPath = 'plugin/plugins/runtime'

        archiveSuffix = System.getenv("PluginSuffix") ?: ""
        archivePrefix = 'plugin'
        destinationDir = "${getRootProject().getBuildDir()}"

        version = 4
        compactVersion = [1, 2, 3]
        uuidNickName = "1.1.5"
    }
}
