[versions]
javassist = "3.28.0-GA"
kotlinxCoroutinesAndroid = "1.7.3"
appcompat = "1.6.1"
constraintlayout = "2.1.0"
material = "1.8.0"
media = "1.6.0"
okhttp3Integration = "4.16.0"
repluginPlugin = "3.1.0"
recyclerview = "1.1.0"
agp = "7.4.0"
kotlin = "1.9.24"
localbroadcastmanager = "1.0.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
slf4jApi = "1.7.5"
viewpager2 = "1.0.0"
gson = "2.10.1"
androidsvg = "1.4"
cardview = "1.0.0"


[libraries]
javassist = { module = "org.javassist:javassist", version.ref = "javassist" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
localbroadcastmanager = { module = "androidx.localbroadcastmanager:localbroadcastmanager", version.ref = "localbroadcastmanager" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material = { module = "com.google.android.material:material", version.ref = "material" }
media = { module = "androidx.media:media", version.ref = "media" }
okhttp3-integration = { module = "com.github.bumptech.glide:okhttp3-integration", version.ref = "okhttp3Integration" }
replugin-host-gradle = { module = "com.qihoo360.replugin:replugin-host-gradle", version.ref = "repluginPlugin" }
replugin-host-lib = { module = "com.qihoo360.replugin:replugin-host-lib", version.ref = "repluginPlugin" }
replugin-plugin-gradle = { module = "com.qihoo360.replugin:replugin-plugin-gradle", version.ref = "repluginPlugin" }
replugin-plugin-lib = { module = "com.qihoo360.replugin:replugin-plugin-lib", version.ref = "repluginPlugin" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4jApi" }
viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
androidsvg = { group = "com.caverock", name = "androidsvg-aar", version.ref = "androidsvg" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

