//plugins {
//    id 'com.android.library'
////    id 'com.android.application'
//    id 'org.jetbrains.kotlin.android'
//}

//apply plugin: 'com.android.application'
apply plugin: 'com.android.library'
//apply plugin: 'com.tencent.shadow.plugin'
apply plugin: 'org.jetbrains.kotlin.android'
apply plugin: 'kotlin-parcelize'
apply plugin: 'replugin-host-gradle'

android {

    compileSdk 33

    defaultConfig {
//        applicationId "com.awell.launcher"
        minSdk 26
        targetSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildFeatures {
        viewBinding true
        aidl true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

//    android.applicationVariants.all {
//        variant ->
//            variant.outputs.all {
//                outputFileName = "Launcher.apk"
//            }
//    }
//    android {
//
//
//        defaultConfig {
//            applicationId "com.awell.launcher"
//            manifestPlaceholders = [sharedUserId: "android.uid.system"]
//        }
//    }


//    buildTypes {
//        release {
//            minifyEnabled false
//            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
//            signingConfig signingConfigs.release
//        }
//    }
    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }
}

dependencies {

    implementation project(':plugin:plugins:host-lib')
//    implementation project(':plugin:plugins:constant')

    //implementation files('libs\\kwmusic.jar')
    //compileOnly files('libs\\mlibrary.jar')

//    implementation (libs.kotlinx.coroutines.android){
//        exclude group: 'org.jetbrains', module: 'annotations'
//    }


    implementation(libs.appcompat) {
        exclude group: 'org.jetbrains.kotlinx'
        exclude group: 'org.jetbrains.kotlin'

    }

    implementation(libs.kotlinx.coroutines.android)

    implementation(libs.constraintlayout) {
        exclude group: 'androidx.appcompat'
    }

    implementation libs.recyclerview
    implementation libs.replugin.host.lib

    compileOnly project(path: ':AwellLibrary')

    implementation libs.media

    implementation libs.localbroadcastmanager

    implementation "org.slf4j:slf4j-api:$slf4j_version"

    implementation(libs.okhttp3.integration) {
        exclude group: 'androidx.core', module: 'core'
        exclude group: 'androidx.interpolator', module: 'interpolator'
        exclude group: 'org.jetbrains.kotlin'
        exclude group: 'org.jetbrains.kotlinx'
    }

}








