{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.shadow.coding",
    "module": "aar-to-jar-plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aar-to-jar-plugin-unspecified.jar",
          "url": "aar-to-jar-plugin-unspecified.jar",
          "size": 5222,
          "sha512": "5e0502e1be68591e17f55d0eb1adfbd110af5302b77cf69b51a4ff5268db9d6c27832e2b99abc9e48d462cea2333d857851e425b6ca3c1fd4d10940b37854310",
          "sha256": "9e9a802e9a7839a856f0bf3b2331a0e8ec4efed83d5ec8d41c2c1ab31a2192a8",
          "sha1": "84901b3c654519e7299465be252ee22b45cc7f39",
          "md5": "faff96aca19ed22c2c7bc0ac57ba794a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "aar-to-jar-plugin-unspecified.jar",
          "url": "aar-to-jar-plugin-unspecified.jar",
          "size": 5222,
          "sha512": "5e0502e1be68591e17f55d0eb1adfbd110af5302b77cf69b51a4ff5268db9d6c27832e2b99abc9e48d462cea2333d857851e425b6ca3c1fd4d10940b37854310",
          "sha256": "9e9a802e9a7839a856f0bf3b2331a0e8ec4efed83d5ec8d41c2c1ab31a2192a8",
          "sha1": "84901b3c654519e7299465be252ee22b45cc7f39",
          "md5": "faff96aca19ed22c2c7bc0ac57ba794a"
        }
      ]
    }
  ]
}
