{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.shadow.coding",
    "module": "aar-to-jar-plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aar-to-jar-plugin-unspecified.jar",
          "url": "aar-to-jar-plugin-unspecified.jar",
          "size": 5222,
          "sha512": "301c332c37b4387088c253e6fdb931ebeb8ce76ff015de0b7abde140f840cd89715a8d50a266532e809d44c12aaec7aca3a6ab7eeb22e9444a49af78ebb23510",
          "sha256": "2b73c0b61aea8e6200271410bd0bc04af0467f9ef454f133b9dd380b8e7d3c24",
          "sha1": "3b6ed49a7bf9d58b6cdec1a9c2ddebf4d8bb9b58",
          "md5": "3b6322a5e4e760d1def9bb6c0483b0be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "aar-to-jar-plugin-unspecified.jar",
          "url": "aar-to-jar-plugin-unspecified.jar",
          "size": 5222,
          "sha512": "301c332c37b4387088c253e6fdb931ebeb8ce76ff015de0b7abde140f840cd89715a8d50a266532e809d44c12aaec7aca3a6ab7eeb22e9444a49af78ebb23510",
          "sha256": "2b73c0b61aea8e6200271410bd0bc04af0467f9ef454f133b9dd380b8e7d3c24",
          "sha1": "3b6ed49a7bf9d58b6cdec1a9c2ddebf4d8bb9b58",
          "md5": "3b6322a5e4e760d1def9bb6c0483b0be"
        }
      ]
    }
  ]
}
