//plugins {
//    id 'com.android.application'
//    id 'org.jetbrains.kotlin.android'
//}
buildscript {

    repositories {
        if (!System.getenv().containsKey("DISABLE_TENCENT_MAVEN_MIRROR")) {
            maven { url 'https://mirrors.tencent.com/nexus/repository/maven-public/' }
        } else {
            google()
            mavenCentral()
        }
        maven {
            url = uri(mavenRepoUrl)
        }
        mavenLocal()
    }
    dependencies {
        classpath 'com.tencent.shadow.core:runtime:1.0'
        classpath 'com.tencent.shadow.core:activity-container:1.0'
        classpath 'com.tencent.shadow.core:gradle-plugin:1.0'
        classpath "org.javassist:javassist:$javassist_version"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.0"
    }

}

apply plugin: 'com.android.application'
apply plugin: 'com.tencent.shadow.plugin'
apply plugin: 'org.jetbrains.kotlin.android'


android {
    namespace 'com.example.launcher_plugin'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.launcher_plugin"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    signingConfigs {
        debug {
            storeFile file('../keystore/platform.jks')
            keyAlias 'platform'
            keyPassword 'android'
            storePassword 'android'
        }
        release {
            storeFile file('../keystore/platform.jks')
            keyAlias 'platform'
            keyPassword 'android'
            storePassword 'android'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.2"
    }
    kotlinOptions {
        jvmTarget = '11'
    }
    // 将插件applicationId设置为和宿主相同
    productFlavors {
        plugin {
            applicationId SAMPLE_HOST_APP_APPLICATION_ID
        }
    }
    // 将插件的资源ID分区改为和宿主0x7F不同的值
    aaptOptions {
        additionalParameters "--package-id", "0x7E", "--allow-reserved-package-id"
    }
}

dependencies {

//    implementation 'androidx.core:core-ktx:1.13.0'
//    implementation 'androidx.appcompat:appcompat:1.6.1'
//    implementation 'com.google.android.material:material:1.12.0'
//    implementation 'com.google.android.material:material:1.12.0'

    constraints {
        implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android") {
            version { strictly("1.7.3") } // Kotlin 1.9.x官方推荐协程版本
        }
        implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core") {
            version { strictly("1.7.3") }
        }
    }
    implementation("androidx.lifecycle:lifecycle-common:2.6.1") // 保持原版本
    implementation 'androidx.activity:activity:1.7.1'

    implementation 'androidx.appcompat:appcompat:1.4.1'

    pluginCompileOnly project(path: ':AwellLibrary')
    normalImplementation project(path: ':AwellLibrary')

    pluginCompileOnly project(path: ':app')
    normalImplementation project(path: ':app')

    implementation 'androidx.constraintlayout:constraintlayout:2.0.1'

    pluginCompileOnly 'com.tencent.shadow.core:runtime:1.0'

    //注意host-lib要用compileOnly编译而不打包在插件中。在packagePlugin任务中配置hostWhiteList允许插件访问宿主的类。
    pluginCompileOnly project(":plugin:plugins:host-lib")
    normalImplementation project(":plugin:plugins:host-lib")

}


