plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace 'com.launcher.yfd_ui01'
    compileSdk 34

    defaultConfig {
        applicationId "com.launcher.yfd_ui01"
        minSdk 26
        targetSdk 34
        versionCode 2
        versionName "1.0"

    }
    // 修改 APK 名称
    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            output.outputFileName = "LauncherUI1.apk"
        }
    }
    buildFeatures {
        viewBinding true
    }

    signingConfigs {
        debug {
            storeFile file('../../../keystore/platform.jks')
            keyAlias 'platform'
            keyPassword 'android'
            storePassword 'android'
        }
        release {
            storeFile file('../../../keystore/platform.jks')
            keyAlias 'platform'
            keyPassword 'android'
            storePassword 'android'
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    aaptOptions {
        additionalParameters '--allow-reserved-package-id', '--package-id', '0x7e'
    }
    sourceSets {
        main {
            assets {
                srcDirs 'src\\main\\assets'
            }
        }
    }
}


def isPlugin = true


if (isPlugin) {
    apply plugin: 'replugin-plugin-gradle'
} else {
    apply plugin: 'replugin-host-gradle'
}

dependencies {

    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4'
    implementation libs.appcompat
    implementation libs.androidx.cardview
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:2.6.0"

    /** compileOnly or implementation */
    //if (rootProject.ext.isPlugin) {
    if (isPlugin) {

        implementation(libs.replugin.plugin.lib)

        // 作为插件，compileOnly 方式引入
        compileOnly libs.appcompat

        compileOnly project(path: ':app')
        compileOnly project(path: ':AwellLibrary')

        //编译期 不会打包
        annotationProcessor 'com.github.bumptech.glide:compiler:4.16.0'
        compileOnly libs.recyclerview

        compileOnly(libs.okhttp3.integration) {
            exclude group: 'androidx.core', module: 'core'
            exclude group: 'androidx.interpolator', module: 'interpolator'
            exclude group: 'org.jetbrains.kotlin'
            exclude group: 'org.jetbrains.kotlinx'
        }

        implementation(libs.constraintlayout) {
            exclude group: 'androidx.appcompat'
            exclude group: 'androidx.core'
            exclude group: 'androidx.fragment'
        }

    } else {


        implementation(project(':app')) {
        }

        implementation(libs.appcompat)

        //app module has
        compileOnly libs.constraintlayout

        //system has
        compileOnly project(path: ':AwellLibrary')

        annotationProcessor 'com.github.bumptech.glide:compiler:4.16.0'

        implementation libs.recyclerview

        //app module has
        compileOnly(libs.okhttp3.integration) {
            exclude group: 'androidx.core', module: 'core'
            exclude group: 'androidx.interpolator', module: 'interpolator'
            exclude group: 'org.jetbrains.kotlin'
            exclude group: 'org.jetbrains.kotlinx'
        }
    }
}


if (isPlugin) {
    repluginPluginConfig {
        //插件名
        pluginName = "yfd_plugin01"
        //使用根项目中定义的宿主app包名
        hostApplicationId = rootProject.ext.hostApplicationId
        //使用根项目中定义的宿主app启动activity
        hostAppLauncherActivity = rootProject.ext.hostAppLauncherActivity
//    ignoredInjectors = ['LoaderActivityInjector', 'ProviderInjector']
    }
}